// Data structure remains the same but now contains real district data from survey

export interface District {
  id: string
  name: string
  state: string
  subDistrict?: string
  stateCode: string
  currentGreenCover: number // sq km
  targetedGreenCover: number // sq km
  greeneryDeficit: number // sq km
  totalArea: number // sq km
  priorityIndex: number // 0-100, calculated from deficit
  meanRainfall: number // mm
  meanTemperature: number // celsius
  soilOrganicCarbon: number // %
  population: number
  surfaceWater: number // sq km
  treesPlanted?: number
  districtsImproved?: number
}

// State code mapping
const STATE_CODES: Record<string, string> = {
  "Andaman and Nicobar": "AN",
  "Arunachal Pradesh": "AR",
  Assam: "AS",
  Bihar: "BR",
  Chhattisgarh: "CG",
  Goa: "GA",
  Gujarat: "GJ",
  Haryana: "HR",
  "Himachal Pradesh": "HP",
  Jharkhand: "JH",
  Karnataka: "KN",
  Kerala: "KL",
  "Madhya Pradesh": "MP",
  Maharashtra: "MH",
  Manipur: "MN",
  Meghalaya: "ML",
  Mizoram: "MZ",
  Nagaland: "NL",
  Odisha: "OD",
  Punjab: "PB",
  Rajasthan: "RJ",
  Sikkim: "SK",
  "Tamil Nadu": "TN",
  Telangana: "TG",
  Tripura: "TR",
  "Uttar Pradesh": "UP",
  Uttarakhand: "UT",
  "West Bengal": "WB",
}

// Actual survey data parsed from CSV
const SURVEY_DATA: District[] = [
  {
    id: "cg-1",
    name: "Bijapur",
    state: "Chhattisgarh",
    subDistrict: "Bijapur",
    stateCode: "CG",
    currentGreenCover: 7701.05,
    targetedGreenCover: 2646.12,
    greeneryDeficit: -5054.93,
    totalArea: 8820.41,
    priorityIndex: 30,
    meanRainfall: 1223.7,
    meanTemperature: 26.6,
    soilOrganicCarbon: 26.04,
    population: 238135,
    surfaceWater: 118.15,
  },
  {
    id: "as-1",
    name: "Karbi Anglong",
    state: "Assam",
    subDistrict: "Diphu",
    stateCode: "AS",
    currentGreenCover: 6932.65,
    targetedGreenCover: 2201.34,
    greeneryDeficit: -4731.31,
    totalArea: 7337.81,
    priorityIndex: 25,
    meanRainfall: 1750.66,
    meanTemperature: 23.28,
    soilOrganicCarbon: 36.93,
    population: 599603,
    surfaceWater: 11.72,
  },
  {
    id: "ar-1",
    name: "West Siang",
    state: "Arunachal Pradesh",
    subDistrict: "Along",
    stateCode: "AR",
    currentGreenCover: 6705.84,
    targetedGreenCover: 2342.79,
    greeneryDeficit: -4363.05,
    totalArea: 7809.29,
    priorityIndex: 28,
    meanRainfall: 1781.94,
    meanTemperature: 14.39,
    soilOrganicCarbon: 43.41,
    population: 100730,
    surfaceWater: 29.25,
  },
  {
    id: "od-1",
    name: "Kandhamal",
    state: "Odisha",
    subDistrict: "Ghumsur",
    stateCode: "OD",
    currentGreenCover: 5726.02,
    targetedGreenCover: 1795.88,
    greeneryDeficit: -3930.14,
    totalArea: 5986.26,
    priorityIndex: 35,
    meanRainfall: 1426.79,
    meanTemperature: 24.47,
    soilOrganicCarbon: 31.95,
    population: 520634,
    surfaceWater: 7.92,
  },
  {
    id: "ar-2",
    name: "Upper Siang",
    state: "Arunachal Pradesh",
    subDistrict: "Along",
    stateCode: "AR",
    currentGreenCover: 5975.57,
    targetedGreenCover: 2107.76,
    greeneryDeficit: -3867.81,
    totalArea: 7025.86,
    priorityIndex: 32,
    meanRainfall: 1611.4,
    meanTemperature: 9.91,
    soilOrganicCarbon: 41.82,
    population: 30880,
    surfaceWater: 47.54,
  },
  {
    id: "wb-1",
    name: "Puruliya",
    state: "West Bengal",
    subDistrict: "Puruliya",
    stateCode: "WB",
    currentGreenCover: 5688.77,
    targetedGreenCover: 1881.5,
    greeneryDeficit: -3807.27,
    totalArea: 6271.68,
    priorityIndex: 38,
    meanRainfall: 1202.81,
    meanTemperature: 25.73,
    soilOrganicCarbon: 25.18,
    population: 2915127,
    surfaceWater: 185.94,
  },
  {
    id: "ar-3",
    name: "West Kameng",
    state: "Arunachal Pradesh",
    subDistrict: "Bomdila",
    stateCode: "AR",
    currentGreenCover: 5842.47,
    targetedGreenCover: 2206.47,
    greeneryDeficit: -3636,
    totalArea: 7354.89,
    priorityIndex: 42,
    meanRainfall: 768.95,
    meanTemperature: 9.94,
    soilOrganicCarbon: 40.16,
    population: 97572,
    surfaceWater: 17.95,
  },
  {
    id: "wb-2",
    name: "Pashchim Medinipur",
    state: "West Bengal",
    subDistrict: "Medinipur",
    stateCode: "WB",
    currentGreenCover: 5097.93,
    targetedGreenCover: 1605.8,
    greeneryDeficit: -3492.13,
    totalArea: 5352.67,
    priorityIndex: 40,
    meanRainfall: 1436.84,
    meanTemperature: 26.64,
    soilOrganicCarbon: 28.49,
    population: 3881730,
    surfaceWater: 179.97,
  },
  {
    id: "as-2",
    name: "Dima Hasao",
    state: "Assam",
    subDistrict: "Haflong",
    stateCode: "AS",
    currentGreenCover: 4836.01,
    targetedGreenCover: 1475.74,
    greeneryDeficit: -3360.27,
    totalArea: 4919.12,
    priorityIndex: 39,
    meanRainfall: 1885.91,
    meanTemperature: 22.31,
    soilOrganicCarbon: 39.75,
    population: 252639,
    surfaceWater: 35.41,
  },
  {
    id: "ar-4",
    name: "Changlang",
    state: "Arunachal Pradesh",
    subDistrict: "n.a. ( 347)",
    stateCode: "AR",
    currentGreenCover: 4785.59,
    targetedGreenCover: 1513.33,
    greeneryDeficit: -3272.26,
    totalArea: 5044.45,
    priorityIndex: 45,
    meanRainfall: 2566.41,
    meanTemperature: 17.6,
    soilOrganicCarbon: 46.16,
    population: 156693,
    surfaceWater: 21.9,
  },
  {
    id: "ar-5",
    name: "Upper Subansiri",
    state: "Arunachal Pradesh",
    subDistrict: "Daporijo",
    stateCode: "AR",
    currentGreenCover: 5110.75,
    targetedGreenCover: 1926.34,
    greeneryDeficit: -3184.41,
    totalArea: 6421.15,
    priorityIndex: 43,
    meanRainfall: 1270.82,
    meanTemperature: 10.56,
    soilOrganicCarbon: 43.18,
    population: 103215,
    surfaceWater: 19.48,
  },
  {
    id: "od-2",
    name: "Ganjam",
    state: "Odisha",
    subDistrict: "n.a. ( 1460)",
    stateCode: "OD",
    currentGreenCover: 4418.03,
    targetedGreenCover: 1381.8,
    greeneryDeficit: -3036.23,
    totalArea: 4606,
    priorityIndex: 48,
    meanRainfall: 1324.52,
    meanTemperature: 26.23,
    soilOrganicCarbon: 31.62,
    population: 1117487,
    surfaceWater: 43.47,
  },
  {
    id: "od-3",
    name: "Kalahandi",
    state: "Odisha",
    subDistrict: "Bhawanipatna",
    stateCode: "OD",
    currentGreenCover: 4542.78,
    targetedGreenCover: 1528.53,
    greeneryDeficit: -3014.25,
    totalArea: 5095.11,
    priorityIndex: 46,
    meanRainfall: 1354.67,
    meanTemperature: 25.85,
    soilOrganicCarbon: 26.87,
    population: 831011,
    surfaceWater: 104.05,
  },
  {
    id: "br-1",
    name: "Gaya",
    state: "Bihar",
    subDistrict: "Gaya",
    stateCode: "BR",
    currentGreenCover: 4503.99,
    targetedGreenCover: 1492.86,
    greeneryDeficit: -3011.13,
    totalArea: 4976.19,
    priorityIndex: 46,
    meanRainfall: 861.81,
    meanTemperature: 25.81,
    soilOrganicCarbon: 21.98,
    population: 4665142,
    surfaceWater: 84.91,
  },
  {
    id: "wb-3",
    name: "Bankura",
    state: "West Bengal",
    subDistrict: "Bankura",
    stateCode: "WB",
    currentGreenCover: 4538.88,
    targetedGreenCover: 1536.52,
    greeneryDeficit: -3002.36,
    totalArea: 5121.74,
    priorityIndex: 45,
    meanRainfall: 1256.02,
    meanTemperature: 26.23,
    soilOrganicCarbon: 24.8,
    population: 2463312,
    surfaceWater: 169.15,
  },
  {
    id: "mp-1",
    name: "Seoni",
    state: "Madhya Pradesh",
    subDistrict: "Seoni",
    stateCode: "MP",
    currentGreenCover: 4394.02,
    targetedGreenCover: 1424.83,
    greeneryDeficit: -2969.19,
    totalArea: 4749.42,
    priorityIndex: 48,
    meanRainfall: 1383.93,
    meanTemperature: 25.08,
    soilOrganicCarbon: 21.34,
    population: 807470,
    surfaceWater: 67.33,
  },
  {
    id: "od-4",
    name: "Kendujhar",
    state: "Odisha",
    subDistrict: "Kendujhar",
    stateCode: "OD",
    currentGreenCover: 4286.31,
    targetedGreenCover: 1501.56,
    greeneryDeficit: -2784.75,
    totalArea: 5005.18,
    priorityIndex: 52,
    meanRainfall: 1327.12,
    meanTemperature: 25,
    soilOrganicCarbon: 28.9,
    population: 817202,
    surfaceWater: 38.56,
  },
  {
    id: "jh-1",
    name: "Gumla",
    state: "Jharkhand",
    subDistrict: "Gumla",
    stateCode: "JH",
    currentGreenCover: 4354.75,
    targetedGreenCover: 1613.48,
    greeneryDeficit: -2741.27,
    totalArea: 5378.27,
    priorityIndex: 50,
    meanRainfall: 1049.81,
    meanTemperature: 23.24,
    soilOrganicCarbon: 27.83,
    population: 1086823,
    surfaceWater: 42.42,
  },
  {
    id: "ar-6",
    name: "East Kameng",
    state: "Arunachal Pradesh",
    subDistrict: "Seepa",
    stateCode: "AR",
    currentGreenCover: 3964.65,
    targetedGreenCover: 1229.53,
    greeneryDeficit: -2735.12,
    totalArea: 4098.45,
    priorityIndex: 52,
    meanRainfall: 1483.27,
    meanTemperature: 16.12,
    soilOrganicCarbon: 37.31,
    population: 75154,
    surfaceWater: 12.97,
  },
  {
    id: "ar-7",
    name: "Kurung Kumey",
    state: "Arunachal Pradesh",
    subDistrict: "Itanagar",
    stateCode: "AR",
    currentGreenCover: 4436.49,
    targetedGreenCover: 1719.16,
    greeneryDeficit: -2717.33,
    totalArea: 5730.52,
    priorityIndex: 51,
    meanRainfall: 921.89,
    meanTemperature: 9.98,
    soilOrganicCarbon: 40.38,
    population: 97219,
    surfaceWater: 6.63,
  },
  {
    id: "mp-2",
    name: "Sidhi",
    state: "Madhya Pradesh",
    subDistrict: "Sidhi",
    stateCode: "MP",
    currentGreenCover: 4117.81,
    targetedGreenCover: 1437.24,
    greeneryDeficit: -2680.57,
    totalArea: 4790.82,
    priorityIndex: 54,
    meanRainfall: 785.47,
    meanTemperature: 24.92,
    soilOrganicCarbon: 20.15,
    population: 1108435,
    surfaceWater: 87.05,
  },
  {
    id: "ml-1",
    name: "West Khasi Hills",
    state: "Meghalaya",
    subDistrict: "Nongstoin",
    stateCode: "ML",
    currentGreenCover: 3734.76,
    targetedGreenCover: 1147.26,
    greeneryDeficit: -2587.5,
    totalArea: 3824.2,
    priorityIndex: 57,
    meanRainfall: 2566.82,
    meanTemperature: 20.23,
    soilOrganicCarbon: 45.07,
    population: 291549,
    surfaceWater: 5.52,
  },
  {
    id: "od-5",
    name: "Gajapati",
    state: "Odisha",
    subDistrict: "Paralakhemundi",
    stateCode: "OD",
    currentGreenCover: 3808.76,
    targetedGreenCover: 1224.11,
    greeneryDeficit: -2584.65,
    totalArea: 4080.38,
    priorityIndex: 56,
    meanRainfall: 1112.91,
    meanTemperature: 24.79,
    soilOrganicCarbon: 35.77,
    population: 569446,
    surfaceWater: 25.22,
  },
  {
    id: "ar-8",
    name: "Lower Subansiri",
    state: "Arunachal Pradesh",
    subDistrict: "Itanagar",
    stateCode: "AR",
    currentGreenCover: 3716.96,
    targetedGreenCover: 1138.29,
    greeneryDeficit: -2578.67,
    totalArea: 3794.31,
    priorityIndex: 57,
    meanRainfall: 1674.72,
    meanTemperature: 16.44,
    soilOrganicCarbon: 40.41,
    population: 161987,
    surfaceWater: 13.14,
  },
  {
    id: "od-6",
    name: "Koraput",
    state: "Odisha",
    subDistrict: "Koraput",
    stateCode: "OD",
    currentGreenCover: 4182.74,
    targetedGreenCover: 1617.11,
    greeneryDeficit: -2565.63,
    totalArea: 5390.37,
    priorityIndex: 53,
    meanRainfall: 1421.24,
    meanTemperature: 23.23,
    soilOrganicCarbon: 29.5,
    population: 695302,
    surfaceWater: 174.71,
  },
  {
    id: "od-7",
    name: "Rayagada",
    state: "Odisha",
    subDistrict: "Gunupur",
    stateCode: "OD",
    currentGreenCover: 3802.24,
    targetedGreenCover: 1239.05,
    greeneryDeficit: -2563.19,
    totalArea: 4130.15,
    priorityIndex: 56,
    meanRainfall: 1265.2,
    meanTemperature: 25.66,
    soilOrganicCarbon: 30.34,
    population: 479830,
    surfaceWater: 33.58,
  },
  {
    id: "jh-2",
    name: "Hazaribagh",
    state: "Jharkhand",
    subDistrict: "Hazaribag",
    stateCode: "JH",
    currentGreenCover: 3992.59,
    targetedGreenCover: 1448.39,
    greeneryDeficit: -2544.2,
    totalArea: 4827.98,
    priorityIndex: 54,
    meanRainfall: 1028.18,
    meanTemperature: 24.27,
    soilOrganicCarbon: 25.31,
    population: 2028400,
    surfaceWater: 106.82,
  },
  {
    id: "jh-3",
    name: "Palamu",
    state: "Jharkhand",
    subDistrict: "Daltenganj",
    stateCode: "JH",
    currentGreenCover: 3873.79,
    targetedGreenCover: 1339.6,
    greeneryDeficit: -2534.19,
    totalArea: 4465.35,
    priorityIndex: 54,
    meanRainfall: 804.66,
    meanTemperature: 25.23,
    soilOrganicCarbon: 21.97,
    population: 1999140,
    surfaceWater: 90.91,
  },
  {
    id: "mp-3",
    name: "Dindori",
    state: "Madhya Pradesh",
    subDistrict: "Dindori",
    stateCode: "MP",
    currentGreenCover: 4472.16,
    targetedGreenCover: 1951.39,
    greeneryDeficit: -2520.77,
    totalArea: 6504.62,
    priorityIndex: 51,
    meanRainfall: 1282.57,
    meanTemperature: 23.49,
    soilOrganicCarbon: 23.78,
    population: 851986,
    surfaceWater: 45.42,
  },
]

export const STATES_DATA: Record<string, District[]> = {}

// Group data by state
SURVEY_DATA.forEach((district) => {
  if (!STATES_DATA[district.state]) {
    STATES_DATA[district.state] = []
  }
  STATES_DATA[district.state].push(district)
})

export interface TreeSpecies {
  id: string
  commonName: string
  scientificName: string
  category: "forestry" | "horticulture" | "cover"
  waterRequirement: "drought-tolerant" | "moderate" | "monsoon-friendly"
  soilPreference: string
  growthRate: "slow" | "medium" | "fast"
  nativeToRegions: string[]
  benefits: string[]
}

export const TREE_SPECIES: TreeSpecies[] = [
  {
    id: "sal",
    commonName: "Sal",
    scientificName: "Shorea robusta",
    category: "forestry",
    waterRequirement: "monsoon-friendly",
    soilPreference: "Well-drained laterite",
    growthRate: "medium",
    nativeToRegions: ["Odisha", "Jharkhand", "Arunachal Pradesh", "Assam"],
    benefits: ["Timber production", "Soil stabilization", "Biodiversity support"],
  },
  {
    id: "neem",
    commonName: "Neem",
    scientificName: "Azadirachta indica",
    category: "forestry",
    waterRequirement: "drought-tolerant",
    soilPreference: "Well-drained",
    growthRate: "fast",
    nativeToRegions: ["Madhya Pradesh", "Chhattisgarh", "Bihar"],
    benefits: ["Medicinal", "Air purification", "Erosion control"],
  },
  {
    id: "teak",
    commonName: "Teak",
    scientificName: "Tectona grandis",
    category: "forestry",
    waterRequirement: "monsoon-friendly",
    soilPreference: "Well-drained to laterite",
    growthRate: "medium",
    nativeToRegions: ["Odisha", "Jharkhand"],
    benefits: ["Timber production", "Biodiversity", "Climate resilience"],
  },
  {
    id: "mango",
    commonName: "Mango",
    scientificName: "Mangifera indica",
    category: "horticulture",
    waterRequirement: "moderate",
    soilPreference: "Well-drained alluvial",
    growthRate: "medium",
    nativeToRegions: ["West Bengal", "Bihar", "Odisha"],
    benefits: ["Food production", "Economic value", "Shade"],
  },
  {
    id: "bamboo",
    commonName: "Bamboo",
    scientificName: "Bambusa bambos",
    category: "cover",
    waterRequirement: "monsoon-friendly",
    soilPreference: "Any well-drained",
    growthRate: "fast",
    nativeToRegions: ["Assam", "Arunachal Pradesh", "Meghalaya"],
    benefits: ["Fast growth", "Erosion control", "Economic value"],
  },
  {
    id: "ashoka",
    commonName: "Ashoka",
    scientificName: "Saraca asoca",
    category: "horticulture",
    waterRequirement: "moderate",
    soilPreference: "Well-drained loamy",
    growthRate: "slow",
    nativeToRegions: ["West Bengal", "Odisha"],
    benefits: ["Medicinal", "Ornamental", "Shade"],
  },
]

export interface UserCredit {
  id: string
  amount: number
  reason: string
  timestamp: Date
  verified: boolean
}

export const MOCK_USER = {
  id: "user-1",
  name: "Raj Kumar",
  email: "raj@example.com",
  totalCredits: 450,
  treesCertified: 28,
  districtsFocused: ["Odisha", "Jharkhand", "West Bengal"],
  recentCredits: [
    {
      id: "credit-1",
      amount: 100,
      reason: "Planted 5 sal trees in Kendujhar district (verified)",
      timestamp: new Date("2025-11-01"),
      verified: true,
    },
    {
      id: "credit-2",
      amount: 75,
      reason: "Planted 3 mango trees in Puruliya district",
      timestamp: new Date("2025-10-28"),
      verified: true,
    },
  ] as UserCredit[],
}

export const GLOBAL_IMPACT = {
  treesPlanted: 245000,
  districtsImproved: 12,
  creditsIssued: 1840000,
  areasReforested: 3200, // hectares
}
